### ISSUE TITLE
Login/Register: Show notification messages near the input field

### ISSUE THREAD

**Issue by kiyanov** [ss-ita-kh-001/Event-Manager#73]
Move message box at the top of input field.
Add validation rules for login and password.
email: required.
Password: minlength - 6, maxlength - 16, required.
Add proper messages for each rule. 
See screenshot where to place message for login 
[http://prnt.sc/coueby](http://prnt.sc/coueby)

**Comment by AnnSli** [comment]
Could you please provide me with the mentioned screenshot? Thanks.

**Comment by kiyanov** [comment]
@AnnSli  done
