### ISSUE TITLE
app\features\result-table\controllers\result-table-controller.js

### ISSUE THREAD

**Issue by kiyanov** [ss-ita-kh-001/Event-Manager#78]
Optimize `getSortClass`  function, make it simpler. 
Rename `coloumn` variable.

**Comment by Maryna-Yelakova** [comment]
https://github.com/ss-ita-kh-001/Event-Manager/pull/90

**Comment by Maryna-Yelakova** [comment]
https://github.com/ss-ita-kh-001/Event-Manager/pull/90
